name: Cristian Herrera
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    name: 'E2E CHROME'
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          browser: chrome
        
  EDGE:
    runs-on: ubuntu-20.04
    name: 'E2E EDGE'
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          browser: edge   